// Renders app/methods.md into app/methods.html so the methods page is plain HTML: readable by search and AI crawlers
// that don't run JavaScript, and no Markdown library to download. Run after editing methods.md:
//   node scripts/build-methods.mjs
// tests/methods.test.mjs fails if the page is out of date.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const MARKED = 'https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.2/marked.min.js';
const md = readFileSync('app/methods.md', 'utf8');
const sha = createHash('sha256').update(md).digest('hex');
const mod = { exports: {} };
new Function('module', 'exports', await (await fetch(MARKED)).text())(mod, mod.exports);
const body = mod.exports.marked.parse(md).trim()
  .replace(/<a href="(https?:[^"]+)"/g, '<a href="$1" target="_blank" rel="noopener"');
const page = 'app/methods.html', html = readFileSync(page, 'utf8');
const out = html.replace(/<!-- methods:start[^>]*-->[\s\S]*<!-- methods:end -->/,
  `<!-- methods:start sha256=${sha} (generated by scripts/build-methods.mjs from methods.md; do not edit) -->\n${body}\n<!-- methods:end -->`);
if (out === html && !html.includes(sha)) throw new Error('methods:start/end markers not found in ' + page);
writeFileSync(page, out);
console.log('methods.html updated', sha.slice(0, 12));
