#!/usr/bin/env python3
"""Build app/js/apicodes.js: API state codes and county names, so a US API number names its state and county.

API county codes are the FIPS county codes in every state but Alaska (AOGCC uses its own). County names come from
the Census FIPS lists shipped with the `addfips` package (pip download addfips; unzip; pass its data folder).
Usage: python3 scripts/make-api-codes.py path/to/addfips/data
"""
import csv, json, sys, pathlib

# API Bulletin D12A state codes -> (postal, name, FIPS state code or None offshore)
API_STATES = {
    '01': ('AL', 'Alabama', '01'), '02': ('AZ', 'Arizona', '04'), '03': ('AR', 'Arkansas', '05'), '04': ('CA', 'California', '06'),
    '05': ('CO', 'Colorado', '08'), '06': ('CT', 'Connecticut', '09'), '07': ('DE', 'Delaware', '10'), '08': ('DC', 'District of Columbia', '11'),
    '09': ('FL', 'Florida', '12'), '10': ('GA', 'Georgia', '13'), '11': ('ID', 'Idaho', '16'), '12': ('IL', 'Illinois', '17'),
    '13': ('IN', 'Indiana', '18'), '14': ('IA', 'Iowa', '19'), '15': ('KS', 'Kansas', '20'), '16': ('KY', 'Kentucky', '21'),
    '17': ('LA', 'Louisiana', '22'), '18': ('ME', 'Maine', '23'), '19': ('MD', 'Maryland', '24'), '20': ('MA', 'Massachusetts', '25'),
    '21': ('MI', 'Michigan', '26'), '22': ('MN', 'Minnesota', '27'), '23': ('MS', 'Mississippi', '28'), '24': ('MO', 'Missouri', '29'),
    '25': ('MT', 'Montana', '30'), '26': ('NE', 'Nebraska', '31'), '27': ('NV', 'Nevada', '32'), '28': ('NH', 'New Hampshire', '33'),
    '29': ('NJ', 'New Jersey', '34'), '30': ('NM', 'New Mexico', '35'), '31': ('NY', 'New York', '36'), '32': ('NC', 'North Carolina', '37'),
    '33': ('ND', 'North Dakota', '38'), '34': ('OH', 'Ohio', '39'), '35': ('OK', 'Oklahoma', '40'), '36': ('OR', 'Oregon', '41'),
    '37': ('PA', 'Pennsylvania', '42'), '38': ('RI', 'Rhode Island', '44'), '39': ('SC', 'South Carolina', '45'), '40': ('SD', 'South Dakota', '46'),
    '41': ('TN', 'Tennessee', '47'), '42': ('TX', 'Texas', '48'), '43': ('UT', 'Utah', '49'), '44': ('VT', 'Vermont', '50'),
    '45': ('VA', 'Virginia', '51'), '46': ('WA', 'Washington', '53'), '47': ('WV', 'West Virginia', '54'), '48': ('WI', 'Wisconsin', '55'),
    '49': ('WY', 'Wyoming', '56'), '50': ('AK', 'Alaska', None), '51': ('HI', 'Hawaii', '15'),
    '55': ('AK', 'Alaska offshore', None), '56': ('', 'Pacific offshore (OCS)', None), '60': ('', 'Gulf of Mexico offshore (OCS)', None),
    '61': ('', 'Atlantic offshore (OCS)', None),
}

data = pathlib.Path(sys.argv[1])
names = {}
for year in ('2000', '2010', '2015', '2020'):   # later lists win; older ones keep counties since renamed or merged
    for r in csv.DictReader(open(data / f'counties_{year}.csv', encoding='utf-8')):
        n = r['name']
        for suf in (' County', ' Parish'):
            if n.endswith(suf): n = n[: -len(suf)]
        names.setdefault(r['statefp'], {})[r['countyfp']] = n
counties = {}
for api, (_, _, fips) in API_STATES.items():
    if fips and fips in names: counties[api] = '|'.join(f'{c}{n}' for c, n in sorted(names[fips].items()))
states = {k: [a, n] for k, (a, n, _) in API_STATES.items()}
out = pathlib.Path(__file__).resolve().parent.parent / 'app/js/apicodes.js'
out.write_text(
    '/* API state codes (API Bulletin D12A) and county names (US Census FIPS; API county = FIPS county outside Alaska).\n'
    '   Generated by scripts/make-api-codes.py; do not edit by hand. counties: API state -> "CCCName|CCCName|...". */\n'
    '(function (root) {\n  root.WellerAPICodes = {\n'
    f'    states: {json.dumps(states, separators=(",", ":"))},\n'
    f'    counties: {json.dumps(counties, separators=(",", ":"), ensure_ascii=False)},\n'
    '  };\n})(typeof globalThis !== \'undefined\' ? globalThis : this);\n', encoding='utf-8')
print(out, out.stat().st_size, 'bytes')
